"use client";

import { useEffect, useState } from "react";
import { loadPodcast, savePodcast, type SavedPodcast } from "@/lib/podcast-store";
import { useStudy } from "@/lib/use-study";
import Listen from "./Listen";
import Mascot from "./Mascot";

const WAITING = ["Lia tá passando o café ☕", "Beto tá afinando a voz 🎤", "Escrevendo um roteiro inédito ✍️", "Gravando os locutores 🎙️", "Mixando o episódio 🎧"];

/** On-demand, personal podcast: generated by the server on click, kept in this browser. */
export default function PodcastCard({ topicId }: Readonly<{ topicId: string }>) {
  const { data, progress } = useStudy();
  const [episode, setEpisode] = useState<SavedPodcast | null>(null);
  const [url, setUrl] = useState<string>();
  const [busy, setBusy] = useState(false);
  const [tick, setTick] = useState(0);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    loadPodcast(topicId).then((p) => p && setEpisode(p));
  }, [topicId]);

  // blob -> object URL for <audio>, revoked when the episode changes
  useEffect(() => {
    if (!episode?.audio) return;
    const u = URL.createObjectURL(episode.audio);
    setUrl(u); // eslint-disable-line react-hooks/set-state-in-effect -- derived from a Blob, needs cleanup
    return () => URL.revokeObjectURL(u);
  }, [episode]);

  useEffect(() => {
    if (!busy) return;
    const t = setInterval(() => setTick((n) => n + 1), 6000);
    return () => clearInterval(t);
  }, [busy]);

  async function generate() {
    setBusy(true);
    setTick(0);
    setError(null);
    // personalize with this person's open mistakes in the topic
    const byId = new Map(data?.questions.map((q) => [q.id, q]));
    const mistakes = progress.mistakes
      .filter((m) => !m.resolved && byId.get(m.questionId)?.topicId === topicId)
      .map((m) => byId.get(m.questionId)!.question);
    try {
      const res = await fetch("/api/podcast", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ topicId, mistakes }),
      });
      const json = await res.json().catch(() => null);
      if (!res.ok || !json?.lines) throw new Error(json?.error ?? "Não deu pra gerar agora, tenta de novo.");
      const audio = json.audio ? new Blob([Uint8Array.from(atob(json.audio), (c) => c.charCodeAt(0))], { type: "audio/mpeg" }) : null;
      const p: SavedPodcast = { topicId, title: json.title, lines: json.lines, seconds: json.seconds, audio, at: Date.now() };
      await savePodcast(p);
      setEpisode(p);
      if (!audio) setError("As vozes da IA estão sem cota agora: o episódio vai tocar com a voz do navegador.");
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  }

  const button = (
    <button
      type="button"
      onClick={generate}
      disabled={busy}
      className={`btn-3d w-full rounded-2xl px-5 py-3 text-sm disabled:opacity-60 ${episode ? "border-2 border-zinc-200 bg-white text-sky-600" : "bg-brand-600 text-white"}`}
    >
      {busy ? "Gerando…" : episode ? "🔄 Gerar outro episódio" : "🎙️ Gerar meu podcast"}
    </button>
  );

  return (
    <div className="space-y-3">
      {!episode && !busy && (
        <section className="tile space-y-4 p-5">
          <div className="flex items-center gap-4">
            <span className="relative flex h-14 w-14 shrink-0 items-center justify-center rounded-full border-2 border-zinc-200 bg-zinc-50">
              <Mascot size={44} />
              <span aria-hidden className="absolute -right-1 -bottom-1 text-xl">🎧</span>
            </span>
            <div>
              <h2 className="text-lg">🎙️ Podcast</h2>
              <p className="text-sm font-semibold text-zinc-500">O Beto explica a matéria do zero e a Lia pergunta o que você perguntaria. Focado no que você errou.</p>
            </div>
          </div>
          {button}
        </section>
      )}

      {busy && (
        <section className="tile space-y-3 p-5 text-center" role="status">
          <Mascot size={64} className="mx-auto animate-bounce" />
          <p className="font-extrabold">{WAITING[tick % WAITING.length]}</p>
          <p className="text-sm font-semibold text-zinc-500">Leva uns 1 a 3 min. Pode ir lendo o resumo enquanto isso.</p>
        </section>
      )}

      {episode && !busy && (
        <>
          <Listen
            key={episode.at}
            title={episode.title}
            parts={episode.lines.map((l) => `${l.speaker}: ${l.text}`)}
            episode={url && episode.audio ? { src: url, lines: episode.lines, seconds: episode.seconds } : undefined}
          />
          {button}
        </>
      )}

      {error && (
        <p role="alert" className="rounded-xl bg-rose-50 px-3 py-2 text-sm font-semibold text-rose-700">
          {error}
        </p>
      )}
    </div>
  );
}
